docs/ITInventory/Controllers/OrderHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using ITInventory.Models;
using HDUtilities;
using System.Net;
using System.Data;

namespace ITInventory.Controllers
{
    public class OrderHistoryController : HDController
    {

        ITInventoryEntities db = new ITInventoryEntities();
        //
        // GET: /OrderHistory/
        public ActionResult Index()
        {
            var orderHist = db.OrderProducts.Where(x => x.Order.Submitted != false).OrderBy(x => x.LastEditDateTime).ToList();

            return View(orderHist);
        }
        [HttpPost]
        public ActionResult Update_OrderConfirm(OrderHistoryConfirm OrderHistConfirm, [Bind(Include = "Id, StockLevel")]Product Products, [Bind(Include = "Id,OrderCost,ProductId,QtyOrdered,LastEditUser,LastEditDateTime")] OrderProduct orderProduct, Order ordere, Lot lot)
        {
            var x = OrderHistConfirm.ProductId;
            var orderedProduct = db.OrderProducts.Where(r => r.Id == OrderHistConfirm.CheckId).FirstOrDefault();
            var prod = db.Products.ToList();
            var lotList = db.Lots.ToList();
            var order = db.Orders.Where(r => r.Id == OrderHistConfirm.CheckId).ToList();

            orderedProduct.CheckedIn = true;

            var Product = prod.Where(r => r.Id == OrderHistConfirm.ProductId).FirstOrDefault();

            lotList.Where(r => r.Price == (orderedProduct.OrderCost / orderedProduct.Quantity)).FirstOrDefault().Quantity += OrderHistConfirm.QtyConfirmed;
            db.SaveChanges();

            return View();
        }

         // GET: /OrderProduct/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderProduct orderProduct = db.OrderProducts.Find(id);
            if (orderProduct == null)
            {
                return HttpNotFound();
            }
            return View(orderProduct);
        }

        // GET: /OrderProduct/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /OrderProduct/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,IsOrderProduct,LastEditDateTime,LastEditUser")] OrderProduct orderProduct)
        {
            if (ModelState.IsValid)
            {
                db.OrderProducts.Add(orderProduct);
                orderProduct.LastEditDateTime = DateTime.Now;
                orderProduct.LastEditUser = HDUtilities.UserInformation.GetCurrentUserName();
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(orderProduct);
        }

        // GET: /OrderProduct/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderProduct orderProduct = db.OrderProducts.Find(id);
            if (orderProduct == null)
            {
                return HttpNotFound();
            }
            return View(orderProduct);
        }

        // POST: /OrderProduct/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,IsOrderProduct,LastEditDateTime,LastEditUser")] OrderProduct orderProduct)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orderProduct).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(orderProduct);
        }

        // GET: /OrderProduct/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderProduct orderProduct = db.OrderProducts.Find(id);
            if (orderProduct == null)
            {
                return HttpNotFound();
            }
            return View(orderProduct);
        }

        // POST: /OrderProduct/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OrderProduct orderProduct = db.OrderProducts.Find(id);
            db.OrderProducts.Remove(orderProduct);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

docs/ITInventory/Views/OrderHistory/Delete.cshtml
@model ITInventory.Models.OrderHistory
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vendor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderCost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtyOrdered)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtyOrdered)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastEditDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastEditDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastEditUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastEditUser)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

docs/ITInventory/Views/OrderHistory/Edit.cshtml
@model ITInventory.Models.OrderHistory

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Product.ProductName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product.ProductName)
                @Html.ValidationMessageFor(model => model.Product.ProductName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QtyOrdered, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QtyOrdered)
                @Html.ValidationMessageFor(model => model.QtyOrdered)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderCost, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderCost)
                @Html.ValidationMessageFor(model => model.OrderCost)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsCheckedIn, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsCheckedIn)
                @Html.ValidationMessageFor(model => model.IsCheckedIn)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastEditDateTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastEditDateTime)
                @Html.ValidationMessageFor(model => model.LastEditDateTime)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

docs/ITInventory/Views/OrderHistory/Index.cshtml
@model IEnumerable<ITInventory.Models.OrderProduct>
@{
    ViewBag.Title = "Order History";
}

<h2>Order History</h2>




@(Html.Kendo().Grid(Model)
    .Name("grid")
            .Columns(column =>
            {
                column.Bound(model => model.Product.ProductName).Title("Product");
                column.Bound(model => model.Quantity).Title("Ordered");
                column.Bound(model => model.OrderCost).Title("Total Cost").Format("{0:c}");
                column.Bound(model => model.Product.Vendor.Name).Title("Vendor");
                column.Bound(model => model.LastEditUser);
                column.Bound(model => model.LastEditDateTime);
                column.Template(@<text>@{if(item.CheckedIn == false){
                                             
                                                 <input type="button" id="@item.Quantity" name="@item.ProductId" class="checkInOrder" value="Check-In" />
                                                 <p style="display: none; position: relative; left: -200px; font-size: 10px;">Checked-In</p>
                }
                                         else if (item.CheckedIn)
                                         {
                                                 <p style="font-size: 16px">Checked-In</p>
                                         }
                }</text>);
                column.Bound(model => model.Id);
                column.Template(@<text>@Html.ActionLink("Edit", "Edit", new { id = item.Id }) | @Html.ActionLink("Delete", "Delete", new { id = item.Id })</text>).Width(150);
            })
            .Scrollable()
            .Filterable()
            .Sortable()
            .HtmlAttributes(new { style = "height: 550px;" })
            .Pageable(pageable => pageable
                .Refresh(true)
                .PageSizes(true)
                .PageSizes(new int[] { 10, 20, 100 })
                .ButtonCount(5))
                )
<script>
    
    $(document).on('click', '.checkInOrder', function () {
        var checkIn = true;
        var checkQty = this.id;
        var productId = this.name;
        var checkId = this.parentNode.parentNode.nextSibling.innerText;

        $(this).fadeOut(300);
        $(this.nextElementSibling).delay(300).fadeIn().animate({
            left: '0px',
        });
        $(this.nextElementSibling).animate({
            fontSize: '16px'
        })

        this.parentNode.children[1].innerText = "Checked-In"
        this.disabled = true;

        $.ajax({
            url: "@Url.Action("Update_OrderConfirm", "OrderHistory")",
            type: 'POST',
            contentType: 'application/json',
            data: JSON.stringify({
                QtyConfirmed: checkQty,
                CheckedIn: checkIn,
                ProductId: productId,
                CheckId: checkId
            })
    })
    });
</script>